src/main.rs

The kernel naming schema changed to include a part which is different in
the package and the uname -r output.

Adapt to new kernel naming schema of ArchLinux

---

src/main.rs

Apparently `uname` and `pacman` provided linux version output changed again.

Fix version parsing

---

src/main.rs

The pacman package now seems to include the 'arch' part in the version
as well. To stay compatible with older packages we just remove it as
well.

Adapt to new pacman output

---

.circleci/config.yml
Cargo.lock
Cargo.toml
README.md
src/main.rs

Get installed package version from alpm.
Additionally, don't remove "arch" from the kernel version. Instead, transform Arch package version format to kernel version format.
Structure has been refactored a bit by introducing the `PackageInfo` struct.
This replaces the alpm part of #14. The additional parsing fixes could be implemented inside `cleanup_pkg_version`.

Use libalpm directly to query database btw.

---

.circleci/config.yml
README.md
src/main.rs

cargo-audit seems to require a newer Rust version.

Increase minimal required Rust version to 1.48.0

---

.github/workflows/ci.yml

GitHub actions sets the HOME variable differently then the original
Docker container, thus rustup searches for the toolchains at the wrong
place.

Set RUSTUP_HOME during CI instead of moving to new HOME

---

CHANGELOG.md
src/main.rs

By parsing the kernel package version digit by digit we can check if the
third digit (the patch version) is missing and insert it. I tried to
avoid pulling in any dependencies like regex to do the fix.
Fixes #8

Fix version comparison for kernel package with missing patch version

---

.github/workflows/ci.yml

The advisories have been withdrawn since they don't seem to be security
critical and the problem goes all the way down to the POSIX API.
See https://github.com/rustsec/advisory-db/issues/1190

Remove cargo-audit ignores

---

.github/workflows/ci.yml
README.md

Also mention in the README that Rust 1.63.0 is required. It may still
compile with an older version, but we don't guarantee it.

Bump Rust version to 1.63.0 for CI

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/checks.rs
src/critical_packages_check.rs
src/kernel.rs
src/main.rs
src/package.rs
src/session.rs

This is the first step in fixing #5

Add generic check for packages

---

src/checks.rs
src/kernel.rs

There is more need to reboot if the kernel got updated compared to other system packages.

Distinguish between kernel and system package updates

---

README.md

The alternate underline syntax only supports two heading levels in looks more like restructured text syntax.
(See https://www.markdownguide.org/basic-syntax)

Use markdown style header markup

---

CHANGELOG.md
README.md
src/main.rs

Make notification timeout configurable

---

Cargo.lock
Cargo.toml
src/main.rs

This included the `FromStr` for `Timeout` implementation (https://github.com/hoodie/notify-rust/pull/169) so we can get rid of our custom implementation.

Update notify-rust to 4.7

---

src/package.rs

As reported by clippy:
warning: manual check for common ascii range
--> src/package.rs:19:36
|
19 |         let res = input.find(|ch| !('0'..='9').contains(&ch));
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `ch.is_ascii_digit()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_is_ascii_check
= note: `#[warn(clippy::manual_is_ascii_check)]` on by default

Use is_ascii_digit instead of manual range check

---

.github/workflows/ci.yml
README.md

We generally want the latest version with the latest lints, since Arch will always have the latest Rust version.

Update to Rust 1.70 in CI

---

CHANGELOG.md
src/kernel.rs

Fix detection of the ck-generic- kernel variants

---

.github/workflows/ci.yml

Apparently the glibc is out of date, which makes it impossible to run node inside the container which is needed by the checkout action.

Update system before checkout

---

CHANGELOG.md
src/kernel.rs
src/package.rs

It confused me that it showed the following with kernel 6.7:
Kernel
installed: 6.7.arch3-1 (since 4 days ago)
running:   6.7.0.arch3.1
systemd updated 14 minutes ago
Reboot arch btw
Note that we should reboot because of the systemd update, but since the
kernel versions look different I thought it was due to a bug in version
comparison.
Since we actually use a cleaned up version to compare the running kernel
we can also show it:
Kernel
installed: 6.7.0.arch3.1 (since 4 days ago)
running:   6.7.0.arch3.1
systemd updated 16 minutes ago
Reboot arch btw
Makes it much clearer that the versions are the same. If we want to see
the raw versions before cleanup, we can enable INFO logging:
[2024-01-20T17:07:35Z INFO  reboot_arch_btw::kernel] uname -r output: 6.7.0-arch3-1
[2024-01-20T17:07:35Z INFO …

Print cleaned kernel version

---

.github/workflows/ci.yml

I noticed in https://github.com/rnestler/reboot-arch-btw/pull/169 that the CI didn't trigger.

Run CI on PRs and master

---

CHANGELOG.md
src/critical_packages_check.rs
src/kernel.rs
src/main.rs

Add a `-v`/`--verbose` flag so that kernel version isn't printed every time pacman updates or for MOTD.

Add verbose flag

---

.github/workflows/ci.yml

We will need an up to date Docker container when pacman 7 hits the core repositories. See also #187.

Use Rust 1.80.1 in CI

---

Cargo.lock
Cargo.toml

See https://github.com/hoodie/notify-rust/discussions/175
This reduces the binary size from 4.2M to 2.8M (stripped). Adding an option to completely disable notifications would reduce binary size even further.

Reduce binary sice by switching to libdbus
